[package]
name = "dave"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3


[dependencies]
macroquad = "0.4.13"
macroquad_macro = "0.1.8"
macroquad-tiled = "0.2.1"
macroquad-platformer = "0.2"
